/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface CleanForm {
        "submitButtonText": string;
    }
    interface TelemetryWrapper {
        "componentId": string;
    }
    interface TestComponent {
    }
}
export interface CleanFormCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCleanFormElement;
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLCleanFormElementEventMap {
        "telemetryEvent": any;
    }
    interface HTMLCleanFormElement extends Components.CleanForm, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCleanFormElementEventMap>(type: K, listener: (this: HTMLCleanFormElement, ev: CleanFormCustomEvent<HTMLCleanFormElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCleanFormElementEventMap>(type: K, listener: (this: HTMLCleanFormElement, ev: CleanFormCustomEvent<HTMLCleanFormElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCleanFormElement: {
        prototype: HTMLCleanFormElement;
        new (): HTMLCleanFormElement;
    };
    interface HTMLTelemetryWrapperElement extends Components.TelemetryWrapper, HTMLStencilElement {
    }
    var HTMLTelemetryWrapperElement: {
        prototype: HTMLTelemetryWrapperElement;
        new (): HTMLTelemetryWrapperElement;
    };
    interface HTMLTestComponentElement extends Components.TestComponent, HTMLStencilElement {
    }
    var HTMLTestComponentElement: {
        prototype: HTMLTestComponentElement;
        new (): HTMLTestComponentElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "clean-form": HTMLCleanFormElement;
        "telemetry-wrapper": HTMLTelemetryWrapperElement;
        "test-component": HTMLTestComponentElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface CleanForm {
        "onTelemetryEvent"?: (event: CleanFormCustomEvent<any>) => void;
        "submitButtonText"?: string;
    }
    interface TelemetryWrapper {
        "componentId"?: string;
    }
    interface TestComponent {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "clean-form": CleanForm;
        "telemetry-wrapper": TelemetryWrapper;
        "test-component": TestComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "clean-form": LocalJSX.CleanForm & JSXBase.HTMLAttributes<HTMLCleanFormElement>;
            "telemetry-wrapper": LocalJSX.TelemetryWrapper & JSXBase.HTMLAttributes<HTMLTelemetryWrapperElement>;
            "test-component": LocalJSX.TestComponent & JSXBase.HTMLAttributes<HTMLTestComponentElement>;
        }
    }
}
